# numpy practice

In [2]:
import numpy as np

In [3]:
len(dir(np))

622

In [4]:
###
#main data structure - numpy n-dim array (array)

In [5]:
sal = [50000, 60000,70000, (10.0,'a')] 
print(type(sal), sal)



<class 'list'> [50000, 60000, 70000, (10.0, 'a')]


In [6]:
#to convert the list to an array use numpy
arr = np.array(sal)
print(type(arr),arr)

<class 'numpy.ndarray'> [50000 60000 70000 (10.0, 'a')]


In [7]:
print(arr.size, type(arr), arr.dtype)

4 <class 'numpy.ndarray'> object


In [8]:
#accessing the values

arr1 = np.array([1,2,3,['4'],5])
arr1[0:]
#print(type(arr1[0:]))




array([1, 2, 3, list(['4']), 5], dtype=object)

In [9]:
#modifying the values

arr2 = np.array(range(1,11))
arr2[2]=11

arr2


array([ 1,  2, 11,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#ways to create an array object using numpy
'''
np.array()
np.empty()
np.zeros()
np.ones()
np.linspace()
np.arange()
np.random.rand*()

'''
lst = [1,2,3]
tup=('a','a','b','c')
set1 = {'a','b',11}
dict1 = {'a':'one', 'b':'two'}
#np.array(dict1) #creating a numy array from list of tuple
data = list(dict1.items())
np.array(data)


array([['a', 'one'],
       ['b', 'two']], dtype='<U3')

In [11]:
# multi dimensonal array
arr1 = np.empty(5,dtype=int)
arr2 = np.empty((5,2),dtype=int)
arr3 = np.empty((5,2,3,1,4),dtype=int)
# print(arr1)
# print('/////////////////////////')
# print(arr2)
print('/////////////////////////')
print(arr3)

/////////////////////////
[[[[[-1280404416         587 -1292806944         587]]

   [[    1733235   460455936  -637534208  1685024006]]

   [[ 1516596341  1685024011  1600482421  1752457584]]]


  [[[ 2037386074  1953719668  1735549279     1536627]]

   [[  678559744  -637534208  1668834563        3698]]

   [[     946688   259129344  -637534208  1667194632]]]]



 [[[[ 1600941153       19295     6320896   788529152]]

   [[  151519496    51511564    84542214    17432842]]

   [[   16909334    16908546    67633410    67633410]]]


  [[[   16908546    16908546    16908546    16908546]]

   [[   17040392    17039880    17302028    17039894]]

   [[   17302030    17432846    17433100    17433102]]]]



 [[[[   68289032    16908806    17957134   360317464]]

   [[ 1702132048  1700033651  1919251571  1667194670]]

   [[ 1600941153  1913071967          20        1906]]]


  [[[ 1179012608        5490   103370240  1600063706]]

   [[ 1701667182   182083423  1869438815  1701606756]]

   [[  2

In [12]:
np.zeros((5,2),int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [13]:
np.ones((5,2),bool)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [14]:
# list(range(1,10,2))

In [15]:
np.arange(2,10,3) #arange generates only 1-D array

array([2, 5, 8])

In [16]:
np.linspace(1,30,37) #by default it gives 50 values

array([ 1.        ,  1.80555556,  2.61111111,  3.41666667,  4.22222222,
        5.02777778,  5.83333333,  6.63888889,  7.44444444,  8.25      ,
        9.05555556,  9.86111111, 10.66666667, 11.47222222, 12.27777778,
       13.08333333, 13.88888889, 14.69444444, 15.5       , 16.30555556,
       17.11111111, 17.91666667, 18.72222222, 19.52777778, 20.33333333,
       21.13888889, 21.94444444, 22.75      , 23.55555556, 24.36111111,
       25.16666667, 25.97222222, 26.77777778, 27.58333333, 28.38888889,
       29.19444444, 30.        ])

In [114]:
np.random.randint(1,6)

5

In [18]:
for i in range(1,10):
    print(np.random.randint(5,10))
    

6
7
8
9
8
7
8
5
9


In [19]:
np.random.randint(5,55,10)

array([45, 46, 18, 26, 26, 16, 39,  8, 51, 12])

In [20]:
np.random.randn(6,2,2) #the values follows normal distribution

array([[[ 0.02399367,  0.00617173],
        [ 1.51772301,  1.52161888]],

       [[-1.75680184,  2.13828235],
        [ 0.66468139,  0.37199166]],

       [[-0.22066195,  1.3652475 ],
        [-0.62008834,  0.25489594]],

       [[-1.03399025,  1.49744549],
        [-0.72946735, -1.0939574 ]],

       [[ 0.88084835, -0.66388896],
        [-0.72831817,  0.49970846]],

       [[-0.50439965, -0.25935566],
        [ 1.03692687, -1.07019237]]])

In [21]:
np.random.rand(7,2) #follows unfirom distribution and number are bw 0 - 1

array([[0.00181598, 0.7794226 ],
       [0.57402552, 0.51273309],
       [0.73931797, 0.36409531],
       [0.22029394, 0.10539788],
       [0.94367156, 0.01305865],
       [0.19145521, 0.60881711],
       [0.41735291, 0.47622916]])

In [22]:
#accessing elements of higher dimension array
arr = np.random.rand(6,2)
arr


array([[0.26292592, 0.45163615],
       [0.93708088, 0.12912092],
       [0.46986547, 0.40615705],
       [0.95754512, 0.89900611],
       [0.7760807 , 0.18208891],
       [0.47870997, 0.53736399]])

In [23]:
arr[4][1]

0.18208891238416725

In [24]:
###slicing on n-dim array [row_range, col_range] => [r0:rN, c0:cN]
arr[3:5][:]




array([[0.95754512, 0.89900611],
       [0.7760807 , 0.18208891]])

In [37]:
#operations on array

salary = [30000, 40000, 20000, 40000, 50000]
bonus = [2000, 3000, 5000, 8000, 10000]

#add salary and bonus
total_salary = []

total_salary = [b+s for b,s in zip(salary, bonus)]
total_salary



[32000, 43000, 25000, 48000, 60000]

In [38]:
asalary = np.array(salary)
abonus = np.array(bonus)
asalary+abonus #vector operation #element-wise addition

array([32000, 43000, 25000, 48000, 60000])

In [39]:
print(salary*2)
print(asalary*2) #element-wise multiplication [broadcasting]

[30000, 40000, 20000, 40000, 50000, 30000, 40000, 20000, 40000, 50000]
[ 60000  80000  40000  80000 100000]


In [41]:
#asalary**.2

In [42]:
asalary>10000

array([ True,  True,  True,  True,  True])

In [43]:

asalary[asalary>35000]


array([40000, 40000, 50000])

In [50]:
asalary[~(asalary>35000)] #values less than 35000


20000

In [55]:
#built in functions
#sum, max, min, len
arr.tolist()

list

In [59]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [77]:
arr5 = np.linspace(1,10,10)
arr7 = arr5.reshape(2,5)


In [111]:
#print(arr7)
arr6 = arr7.ravel() #ravel is used to bring the n-dim array back to linear form
np.where(arr6>5)

(array([5, 6, 7, 8, 9], dtype=int64),)

In [89]:
arr1 = np.random.rand(5,3)
arr1

array([[0.70344283, 0.9460837 , 0.07278351],
       [0.14336351, 0.80099237, 0.58347212],
       [0.55698544, 0.81418626, 0.11915532],
       [0.56350133, 0.9433289 , 0.25821175],
       [0.19060346, 0.07050563, 0.6453511 ]])

In [90]:
arr1.sum()

7.411967231780538

In [91]:
arr1.mean()

0.4941311487853692

In [92]:
arr1.min()

0.07050562722628517

In [93]:
arr1.max()

0.9460837044499508

In [94]:
arr1.size

15

In [100]:
arr1.T #gives the transpose of the matrix (row becomes column and column becomes rows)

array([[0.70344283, 0.14336351, 0.55698544, 0.56350133, 0.19060346],
       [0.9460837 , 0.80099237, 0.81418626, 0.9433289 , 0.07050563],
       [0.07278351, 0.58347212, 0.11915532, 0.25821175, 0.6453511 ]])

In [112]:
print(arr1)
np.where(arr1>0.05)

[[0.70344283 0.9460837  0.07278351]
 [0.14336351 0.80099237 0.58347212]
 [0.55698544 0.81418626 0.11915532]
 [0.56350133 0.9433289  0.25821175]
 [0.19060346 0.07050563 0.6453511 ]]


(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [106]:
# a = np.array([[1, 2, 3], [4, 5, 6]])
  
# print(a)
  
# print ('Indices of elements <4')
  
# b = np.where(a<4)
# print(b)
  
# print("Elements which are <4")
# print(a[b])

[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))
Elements which are <4
[1 2 3]


In [113]:
#np.where(), arr1.corr(), arr1.std(), arr1.argmax(), arr1.argmin(), arr1.all(), arr1.any(), arr1.astype()